const customIcons= {
    seo:"/assets/imgs/icon/seo.svg",
    smm:"/assets/imgs/icon/smm.png",
    smo:"/assets/imgs/icon/smo.png",
    ppc:"/assets/imgs/icon/ppc.png",
    cm:"/assets/imgs/icon/cm.png",
    em:"/assets/imgs/icon/em.png",
    js:"/assets/imgs/icon/js.png",
    mongodb:"/assets/imgs/icon/mongodb.svg",
    woo:"/assets/imgs/icon/woo.svg",
    cSurf:"/assets/imgs/icon/c-surf.png",
    dontnet:"/assets/imgs/icon/dotnet.svg",
    cakephp:"/assets/imgs/icon/cakephp.svg",
    ux:"/assets/imgs/icon/ux.png",
    app:"/assets/imgs/icon/app.png",
    brand:"/assets/imgs/icon/brand.png",
    adBanner:"/assets/imgs/icon/ad-banner.png",
    chatbot:"/assets/imgs/icon/chatbot.png",
    system:"/assets/imgs/icon/system-management.png",
    machine:"/assets/imgs/icon/machine-learning.png",
    deep:"/assets/imgs/icon/deep-learning.png",
    nlp:"/assets/imgs/icon/nlp.png",
    cloud:"/assets/imgs/icon/cloud-development.png",
    pipeline:"/assets/imgs/icon/pipeline.png",
    docker:"/assets/imgs/icon/docker.png",
    architecture:"/assets/imgs/icon/architecture.png",
    hybrid:"/assets/imgs/icon/hybrid.png",
    kotlin:"/assets/imgs/icon/kotlin.png",
    pwa:"/assets/imgs/icon/pwa.png",
    games:"/assets/imgs/icon/games.png",
    unity:"/assets/imgs/icon/unity.png",
    ar:"/assets/imgs/icon/ar.png",
}

export default customIcons